[![Open in Visual Studio Code](https://classroom.github.com/assets/open-in-vscode-718a45dd9cf7e7f842a935f5ebbe5719a5e09af4491e668f4dbf3b35d5cca122.svg)](https://classroom.github.com/online_ide?assignment_repo_id=10250800&assignment_repo_type=AssignmentRepo)
= Projet : tp_qualite

Ce projet est un projet Maven. Il est donc possible de le compiler et de le tester avec Maven.

== Compilation et exécution du projet

=== Prérequis

- Java JDK 11 ou supérieur
- Maven 3.x.x ou supérieur

=== Étapes 

. Cloner le repository git ou télécharger le code source et extraire les fichiers
+
. Ouvrir un terminal ou une invite de commande
+
. Se placer dans le répertoire du projet
+
. Exécuter la commande `mvn clean` pour supprimer les fichiers générés lors de la compilation précédente
+
. Exécuter la commande `mvn compile` pour compiler les fichiers sources du projet
+
. Exécuter la commande `mvn package` pour créer un fichier JAR exécutable
+
. Exécuter la commande `java -jar target/tp_qualite-1.0.jar` pour lancer l'application

L'application devrait maintenant être en cours d'exécution.

== documentation
=== Javadoc

Pour générer la documentation Javadoc, exécutez la commande suivante dans le répertoire racine du projet :
....
mvn javadoc:javadoc
....

La documentation Javadoc sera générée dans le répertoire `target/site/apidocs`. Pour la consulter, ouvrez le fichier `index.html` dans votre navigateur.